### ISSUE TITLE
usage bar in console is inaccurate

### ISSUE THREAD

**Issue by heyjay44** [w3s-project/w3up#1437] opened 2024-05-06 15:44 UTC
Currently, console is showing 0 for folks who are using storage. This prevents us from implementing overage billing. 

Tasks
- [ ] fix console usage bar
- [ ] check that CLI usage command (IIRC, we have one) also shows accurate information

What success looks like:
- [ ] users can see how much storage they are using in console + the CLI

How we will verify this:
- [ ] compare overage billing to one of our accounts for accuracy, otherwise we will have a lot of questions rolling in

**Comment by prodalex** [comment] 2024-05-06 15:58
Duplicate of https://github.com/w3s-project/project-tracking/issues/75

**Closed** 2024-05-06 15:58 UTC
